config/routes.rb
Snet::Application.routes.draw do

  resources :jobs do
    resources :regions
    resources :stations do
      get 'dotting', on: :collection
      post 'mst', on: :collection
    end
  end

  devise_for :users
  root 'jobs#index'

  resources :graphs do
    post 'get_mst', on: :collection
    resources :nodes
    resources :edges
  end

end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_form.html.haml
= form_for @graph do |f|
  - if @graph.errors.any?
    #error_explanation
      %h2= "#{pluralize(@graph.errors.count, "error")} prohibited this graph from being saved:"
      %ul
        - @graph.errors.full_messages.each do |msg|
          %li= msg
  = f.label :name
  = f.text_field :name


  .actions
    = f.submit 'Save'

app/views/graphs/edit.html.haml
%h1 Editing graph

= render 'form'

= link_to 'Show', @graph
\|
= link_to 'Back', graphs_path

app/views/graphs/index.html.haml
%h1 Listing graphs

%table
  %tr
    %th
      Name
    %th
    %th
    %th

  - @graphs.each do |graph|

    %tr
      %td= graph.name
      %td= link_to 'Show', graph
      %td= link_to 'Edit', edit_graph_path(graph)
      %td= link_to 'Destroy', graph, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Graph', new_graph_path

app/views/graphs/new.html.haml
%h1 New graph

= render 'form'

= link_to 'Back', graphs_path

app/views/graphs/show.html.haml
%p#notice= notice
.row
  .col-md-8
    #map
  .col-md-4
    .edge
      %span
        Add Edge
      .form-group
        %label.control-label{for: :start_node} Start
        = select_tag :start_node, options_for_select(@graph.nodes.map {|n| [n.name, n.id]})
      .form-group
        %label.control-label{for: :end_node} End
        = select_tag :end_node,   options_for_select(@graph.nodes.map {|n| [n.name, n.id]})
      %button#add_edge
        submit!


\|
= link_to 'Back', graphs_path
= javascript_include_tag "graphs", "data-turbolinks-track" => false